# Generated by Django 3.2.23 on 2024-11-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='green_listed',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reported',
        ),
    ]
