# Generated by Django 3.2.23 on 2024-11-12 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_alter_post_id'),
        ('comments', '0003_alter_comment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.IntegerField(choices=[(1, 'Graphic violence'), (2, 'Explicit sexual content'), (3, 'Sexualization of minors'), (3, 'Inciting hatred'), (4, 'Encouraging suicide or self-harm'), (5, 'Attempting to defraud'), (6, 'Advertising illegal products'), (7, 'Blatant copyright infringement'), (8, "Other serious reason (please describe in 'explanation')")])),
                ('explanation', models.TextField(blank=True)),
                ('made_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reported_comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
                ('reported_post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'ordering': ['-made_at'],
            },
        ),
    ]
