# Generated by Django 3.2.23 on 2024-11-16 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20241116_1314'),
        ('reports', '0003_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['made_at']},
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='posts.post'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='report',
            name='owner',
        ),
    ]
