# Generated by Django 3.2.23 on 2024-11-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['made_at']},
        ),
    ]
