# Generated by Django 3.2.23 on 2024-11-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.IntegerField(choices=[(1, 'Graphic violence'), (2, 'Explicit sexual content'), (3, 'Sexualization of minors'), (4, 'Inciting hatred'), (5, 'Encouraging suicide or self-harm'), (6, 'Attempting to defraud'), (7, 'Advertising illegal products'), (8, 'Blatant copyright infringement'), (9, "Other serious reason (please describe in 'explanation')")]),
        ),
    ]
