# Generated by Django 3.2.23 on 2024-11-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='post_image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='post_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='post_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
