# Generated by Django 3.2.23 on 2024-11-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_report_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='post_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='post_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='report',
            name='owner',
        ),
    ]
