# Generated by Django 3.2.23 on 2024-11-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0004_auto_20241116_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_at', models.DateTimeField(auto_now_add=True)),
                ('green_listed_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_listed', to='posts.post')),
            ],
            options={
                'ordering': ['-made_at'],
            },
        ),
    ]
